export const homeObjectOne = {
  respDisplay: "none",
  videoDisplay: "none",
  imgDisplay: "flex",
  id: "home",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "شرکت تولیدی و  دندان پزشکی ایده آل ماکو",
  headLine: "نیم قرن تحقیق و توسعه در صنعت دندان ",
  description:
    " اولین تولید کننده دندان کامپوزیت در خاورمیانه  همچنین دومین تولید کننده دندانهای نانو کامپوزیتی در جهان تنها تولید کننده مسواک و خمیردندان تحت لیسانس بست دنتال آلمان در ایران و خاورمیانه , همچنین نماینده شرکت بست دنتال آلمان در خاورمیانه. ",
  buttonLable: "شروع از همین جا",
  btnLink:"/login",
  imgStart: false,
  img: "./images/mod2.png",
  alt: "vaccine",
  dark: true,
  primary: true,
  darkText: true,
};

export const homeObjectTwo = {
  respDisplay: "none",
  id: "product",
  lightBg: false,
  lightText: true,
  lightTextDesc: false,
  topLine: "محصولات ما",
  headLine: "چهل سال تلاش مستمر در تولید دندان",
  description:
    " اولین و بزرگترین , تولیدکننده و صادرکننده دندان های مصنوعی در ایران که در بازار های جهانی نیز توانسته جایگاهی در بین محصولات دندان با کیفیت, برای خود اختصاص دهد  ",
  buttonLable: "مشاهده محصولات",
  btnLink:"/products/dentures",
  imgStart: true,
  img: "./images/product.png",
  alt: "services",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjectThree = {
  respDisplay: "none",
  id: "honers",
  lightBg: false,
  lightText: true,
  lightTextDesc: false,
  topLine: "گواهی و افتخارات",
  headLine:
    "رضایت استفاده کنندگان از محصولات ایده آل ماکو بزرگترین افتخار ماست",
  description:
    " مجموعه صنعتی و دانش بنیان ایده آل ماکو از شروع فعالیت خود در تلاش بود با تیم تحقیق و توسعه پویا و دانشگاه محور کیفیت محصولات خود را در حد جهانی بالا ببرد و در حال حاضر تحقیقات تخصصی ایده ماکو به عنوان سند در منابع آموزشی استفاده میشود..  ",
  buttonLable: "گواهی و افتخارات",
  btnLink:"/base/honer",
  imgStart: false,
  img: "./images/40year.png",
  alt: "services",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjectFour = {
  respDisplay: "none",
  id: "news",
  lightBg: true,
  lightText: true,
  lightTextDesc: false,
  topLine: "وبلاگ و خبرنامه",
  headLine: "   تکنولوژی های روز صنعت دندان را با خبرنامه ایده آل ماکو دنبال کنید",
  description: "منابع آموزشی , سمینارهای تخصصی , حضور در نمایشگاه های بین المللی , تحقیقات آزمایشگاهی , گام به گام در کنارتان هستیم. ",
  buttonLable: "ثبت نام در خبرنامه",
  btnLink:"/login",
  img: "./images/is52.jpg",
  alt: "1234",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjectFive = {
  respDisplay: "none",
  id: "about",
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "ارتباط با ما",
  headLine: "شماره دفتر مرکزی: 88899776-88897672-88897237--021 ",
  description: "آدرس :تهران، منطقه 6، محله وصال شیرازی، م. ولی عصر، ضلع جنوبی بلوار کشاورز، پلاک 22، طبقه پنجم کد پستی : 1416773117",
  buttonLable: "تماس با ما",
  btnLink:"/login",
  btnDisplay:"none",
  imgStart: false,
  img: "./images/about-us1.png",
  videoDisplay: "flex",
  details:"flex",
  imgDisplay: "none",
  alt: "vaccine",
  dark: true,
  primary: true,
  darkText: true,
};
